# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # Your organisation's details
  class Account < BaseModel
    # the unique identifier for this resource
    # @return [UUID | String]
    attr_accessor :id

    # the type of resource
    # @return [String]
    attr_accessor :type

    # the name for the account
    # @return [String]
    attr_accessor :name

    # name identifying the account
    # @return [String]
    attr_accessor :nickname

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash['name'] = 'name'
      @_hash['nickname'] = 'nickname'
      @_hash
    end

    def initialize(id = nil,
                   type = nil,
                   name = nil,
                   nickname = nil)
      @id = id
      @type = type
      @name = name
      @nickname = nickname
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      type = hash['type']
      name = hash['name']
      nickname = hash['nickname']

      # Create object from extracted values.
      Account.new(id,
                  type,
                  name,
                  nickname)
    end
  end
end
