# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the bank account associated with this contact
  class BankAccount < BaseModel
    # the unique identifier for the bank account
    # @return [UUID | String]
    attr_accessor :id

    # the type of resource
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash
    end

    def initialize(id = nil,
                   type = nil)
      @id = id
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      type = hash['type']

      # Create object from extracted values.
      BankAccount.new(id,
                      type)
    end
  end
end
