# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the category of this journal entry
  class CategoryEnum
    CATEGORY_ENUM = [
      # TODO: Write general description for PAYMENT
      PAYMENT = 'payment'.freeze,

      # TODO: Write general description for PAYMENT_REQUEST
      PAYMENT_REQUEST = 'payment_request'.freeze,

      # TODO: Write general description for REFUND
      REFUND = 'refund'.freeze,

      # TODO: Write general description for INVOICE
      INVOICE = 'invoice'.freeze
    ].freeze
  end
end
