# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the status of this journal entry
  class ChangedStatusEnum
    CHANGED_STATUS_ENUM = [
      # TODO: Write general description for DEBIT_MATURING
      DEBIT_MATURING = 'debit_maturing'.freeze,

      # TODO: Write general description for DEBIT_MATURED
      DEBIT_MATURED = 'debit_matured'.freeze,

      # TODO: Write general description for DEBIT_PROCESSING
      DEBIT_PROCESSING = 'debit_processing'.freeze,

      # TODO: Write general description for DEBIT_CLEARING
      DEBIT_CLEARING = 'debit_clearing'.freeze,

      # TODO: Write general description for DEBIT_REJECTED
      DEBIT_REJECTED = 'debit_rejected'.freeze,

      # TODO: Write general description for DEBIT_CLEARED
      DEBIT_CLEARED = 'debit_cleared'.freeze,

      # TODO: Write general description for DEBIT_RETURNED
      DEBIT_RETURNED = 'debit_returned'.freeze,

      # TODO: Write general description for DEBIT_VOIDED
      DEBIT_VOIDED = 'debit_voided'.freeze,

      # TODO: Write general description for DEBIT_PENDING_VERIFICATION
      DEBIT_PENDING_VERIFICATION = 'debit_pending_verification'.freeze,

      # TODO: Write general description for DEBIT_PAUSED
      DEBIT_PAUSED = 'debit_paused'.freeze,

      # TODO: Write general description for DEBIT_PREFAILED
      DEBIT_PREFAILED = 'debit_prefailed'.freeze,

      # TODO: Write general description for DEBIT_PREPROCESSING
      DEBIT_PREPROCESSING = 'debit_preprocessing'.freeze,

      # TODO: Write general description for CREDIT_MATURING
      CREDIT_MATURING = 'credit_maturing'.freeze,

      # TODO: Write general description for CREDIT_MATURED
      CREDIT_MATURED = 'credit_matured'.freeze,

      # TODO: Write general description for CREDIT_PROCESSING
      CREDIT_PROCESSING = 'credit_processing'.freeze,

      # TODO: Write general description for CREDIT_CLEARING
      CREDIT_CLEARING = 'credit_clearing'.freeze,

      # TODO: Write general description for CREDIT_REJECTED
      CREDIT_REJECTED = 'credit_rejected'.freeze,

      # TODO: Write general description for CREDIT_CLEARED
      CREDIT_CLEARED = 'credit_cleared'.freeze,

      # TODO: Write general description for CREDIT_RETURNED
      CREDIT_RETURNED = 'credit_returned'.freeze,

      # TODO: Write general description for CREDIT_VOIDED
      CREDIT_VOIDED = 'credit_voided'.freeze,

      # TODO: Write general description for CREDIT_PENDING_VERIFICATION
      CREDIT_PENDING_VERIFICATION = 'credit_pending_verification'.freeze,

      # TODO: Write general description for CREDIT_PAUSED
      CREDIT_PAUSED = 'credit_paused'.freeze,

      # TODO: Write general description for CREDIT_PREFAILED
      CREDIT_PREFAILED = 'credit_prefailed'.freeze,

      # TODO: Write general description for CREDIT_PREPROCESSING
      CREDIT_PREPROCESSING = 'credit_preprocessing'.freeze,

      # TODO: Write general description for REVERSAL_MATURING
      REVERSAL_MATURING = 'reversal_maturing'.freeze,

      # TODO: Write general description for REVERSAL_MATURED
      REVERSAL_MATURED = 'reversal_matured'.freeze,

      # TODO: Write general description for REVERSAL_PROCESSING
      REVERSAL_PROCESSING = 'reversal_processing'.freeze,

      # TODO: Write general description for REVERSAL_CLEARING
      REVERSAL_CLEARING = 'reversal_clearing'.freeze,

      # TODO: Write general description for REVERSAL_REJECTED
      REVERSAL_REJECTED = 'reversal_rejected'.freeze,

      # TODO: Write general description for REVERSAL_CLEARED
      REVERSAL_CLEARED = 'reversal_cleared'.freeze,

      # TODO: Write general description for REVERSAL_RETURNED
      REVERSAL_RETURNED = 'reversal_returned'.freeze,

      # TODO: Write general description for REVERSAL_VOIDED
      REVERSAL_VOIDED = 'reversal_voided'.freeze,

      # TODO: Write general description for REVERSAL_PENDING_VERIFICATION
      REVERSAL_PENDING_VERIFICATION = 'reversal_pending_verification'.freeze,

      # TODO: Write general description for REVERSAL_PAUSED
      REVERSAL_PAUSED = 'reversal_paused'.freeze,

      # TODO: Write general description for REVERSAL_PREFAILED
      REVERSAL_PREFAILED = 'reversal_prefailed'.freeze,

      # TODO: Write general description for REVERSAL_PREPROCESSING
      REVERSAL_PREPROCESSING = 'reversal_preprocessing'.freeze
    ].freeze
  end
end
