# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the entry type of this transaction
  class EntryType1Enum
    ENTRY_TYPE1_ENUM = [
      # TODO: Write general description for DEBIT
      DEBIT = 'debit'.freeze,

      # TODO: Write general description for CREDIT
      CREDIT = 'credit'.freeze
    ].freeze
  end
end
