# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # Pagination Model.
  class Pagination < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :first

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mnext

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first'] = 'first'
      @_hash['mnext'] = 'next'
      @_hash
    end

    def initialize(first = nil,
                   mnext = nil)
      @first = first
      @mnext = mnext
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first = hash['first']
      mnext = hash['next']

      # Create object from extracted values.
      Pagination.new(first,
                     mnext)
    end
  end
end
