# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # sort1.
  class Sort1Enum
    SORT1_ENUM = [
      # TODO: Write general description for NAME
      NAME = 'name'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for NICKNAME
      NICKNAME = 'nickname'.freeze
    ].freeze
  end
end
