# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # sort.
  class SortEnum
    SORT_ENUM = [
      # TODO: Write general description for COUNTER_PARTY
      COUNTER_PARTY = 'counter_party'.freeze
    ].freeze
  end
end
