# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # sort2.
  class Sort2Enum
    SORT2_ENUM = [
      # TODO: Write general description for COUNTER_PARTY
      COUNTER_PARTY = 'counter_party'.freeze,

      # TODO: Write general description for STATUS_CHANGED_AT
      STATUS_CHANGED_AT = 'status_changed_at'.freeze
    ].freeze
  end
end
