# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the current status of this journal entry
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for MATURING
      MATURING = 'maturing'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'processing'.freeze,

      # TODO: Write general description for REVERSING
      REVERSING = 'reversing'.freeze,

      # TODO: Write general description for PAUSED
      PAUSED = 'paused'.freeze,

      # TODO: Write general description for PROCESSED
      PROCESSED = 'processed'.freeze,

      # TODO: Write general description for VOIDED
      VOIDED = 'voided'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for REVERSED
      REVERSED = 'reversed'.freeze
    ].freeze
  end
end
