# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # the HTTP status code applicable to this problem
  class Status2Enum
    STATUS2_ENUM = [
      # TODO: Write general description for ENUM_400
      ENUM_400 = 400,

      # TODO: Write general description for ENUM_401
      ENUM_401 = 401,

      # TODO: Write general description for ENUM_403
      ENUM_403 = 403,

      # TODO: Write general description for ENUM_404
      ENUM_404 = 404,

      # TODO: Write general description for ENUM_406
      ENUM_406 = 406,

      # TODO: Write general description for ENUM_415
      ENUM_415 = 415,

      # TODO: Write general description for ENUM_422
      ENUM_422 = 422,

      # TODO: Write general description for ENUM_429
      ENUM_429 = 429,

      # TODO: Write general description for ENUM_500
      ENUM_500 = 500
    ].freeze
  end
end
