# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  #  split_apiv2 client class.
  class SplitApiv2Client
    # Singleton access to client controller.
    # @return [APIController] Returns the controller instance.
    def client
      APIController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(authorization: nil)
      Configuration.authorization = authorization if
        authorization
    end
  end
end
