# split_apiv2
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module SplitApiv2
  # error_response class.
  class ErrorResponseException < APIException
    # TODO: Write general description for this method
    # @return [List of Error]
    attr_accessor :errors

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :meta

    # The constructor.
    # @param [String] The reason for raising an exception.
    # @param [HttpContext] The HttpContext of the API call.
    def initialize(reason, context)
      super(reason, context)
      hash = APIHelper.json_deserialize(@context.response.raw_body)
      unbox(hash)
    end

    # Populates this object by extracting properties from a hash.
    # @param [Hash] The deserialized response sent by the server in the
    # response body.
    def unbox(hash)
      # Parameter is an array, so we need to iterate through it
      @errors = nil
      unless hash['errors'].nil?
        @errors = []
        hash['errors'].each do |structure|
          @errors << (Error.from_hash(structure) if structure)
        end
      end
      @meta = hash['meta']
    end
  end
end
